# Generated by Django 2.0.2 on 2018-02-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_url',
            field=models.URLField(blank=True, verbose_name='School URL'),
        ),
        migrations.AlterField(
            model_name='education',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='region',
            field=models.CharField(blank=True, help_text='e.g. state such as Massachusetts', max_length=255),
        ),
    ]
