# Generated by Django 2.0.2 on 2018-03-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('link', models.URLField(blank=True, verbose_name='School URL')),
                ('linkname', models.URLField(blank=True, default='this link')),
            ],
            options={
                'ordering': ['order', 'id'],
                'db_table': 'achievement',
            },
        ),
    ]
