# Generated by Django 2.0.2 on 2018-03-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='linkname',
            field=models.URLField(blank=True, default=''),
        ),
    ]
