# Generated by Django 2.0.2 on 2018-02-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180221_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completion_date',
            field=models.DateField(blank=True),
        ),
    ]
