# Generated by Django 2.0.2 on 2018-03-04 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_skill_skillurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['vote', 'id']},
        ),
        migrations.RemoveField(
            model_name='language',
            name='ordering',
        ),
        migrations.AddField(
            model_name='language',
            name='vote',
            field=models.IntegerField(blank=True, help_text='Kill level 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
