# Generated by Django 2.0.2 on 2018-02-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20180224_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-end_date', '-start_date']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='completion_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
