# Generated by Django 2.0.2 on 2018-02-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20180224_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='region_shorthand',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='region',
            field=models.CharField(blank=True, help_text='e.g. MA or Italy', max_length=255),
        ),
    ]
