# Generated by Django 2.0.2 on 2018-03-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20180303_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['level', 'id']},
        ),
        migrations.RemoveField(
            model_name='language',
            name='vote',
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[(5, 'Native'), (4, 'Full professional proficiency'), (3, 'Professional working proficiency'), (2, 'Limited professional proficiency'), (1, 'Elementary professional proficiency')], max_length=25),
        ),
    ]
