# Generated by Django 2.0.2 on 2018-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20180224_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
