# Generated by Django 2.0.2 on 2018-02-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20180224_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=30)),
                ('ordering', models.IntegerField(default=1)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='accomplishment',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
