# Generated by Django 2.0.2 on 2018-02-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_personalinfo_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='sitename',
            field=models.CharField(default=models.URLField(blank=True), max_length=255),
        ),
    ]
