# Generated by Django 2.0.2 on 2018-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_personalinfo_sitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='twittername',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
