# Generated by Django 2.0.2 on 2018-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_personalinfo_twittername'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Developer', max_length=255),
        ),
    ]
