# Generated by Django 2.0.2 on 2018-02-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_education_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
    ]
