# Generated by Django 2.0.2 on 2018-02-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_remove_language_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
