# Generated by Django 2.0.2 on 2018-02-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_education_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
