# Generated by Django 2.0.2 on 2018-02-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=30)),
                ('ordering', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
