# Generated by Django 2.0.2 on 2018-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='facebook',
            field=models.URLField(blank=True),
        ),
    ]
