# Generated by Django 2.0.2 on 2018-03-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_remove_personalinfo_sitename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='summary',
            new_name='degree',
        ),
    ]
