# Generated by Django 2.0.3 on 2018-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0038_auto_20180331_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to='resume/static/img'),
        ),
    ]
