# Generated by Django 2.0.3 on 2018-03-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0042_auto_20180331_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
