# Generated by Django 2.0.3 on 2018-03-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0045_remove_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.FileField(blank=True, upload_to='static/resume/img/'),
        ),
    ]
