# Generated by Django 2.0.3 on 2018-03-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0047_auto_20180331_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/resume/img/'),
        ),
    ]
