# Generated by Django 2.0.3 on 2018-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0048_auto_20180331_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/resume/img/'),
        ),
    ]
