# Generated by Django 2.0.3 on 2018-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0049_personalinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, help_text='Text shown in modals appearing when clicking on images'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, help_text='Text shown in project list'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Preferred width x height: 247x200', upload_to='static/resume/img/'),
        ),
    ]
