# Generated by Django 2.0.3 on 2018-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0050_auto_20180408_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='cv_pdf',
            field=models.FileField(blank=True, help_text='Downloadable resume file', upload_to='static/resume/img/'),
        ),
    ]
