# Generated by Django 2.1.4 on 2018-12-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0051_personalinfo_cv_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_pdf',
            field=models.FileField(blank=True, help_text='Downloadable file', upload_to='static/resume/img/'),
        ),
    ]
