# Generated by Django 2.0.3 on 2018-12-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0052_achievement_achievement_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='addendum',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
